typography_spectrum: 0.015139973722398281
color:
  brandColors:
    - '#5A1F00'
    - '#D1570D'
    - '#FDE792'
    - '#477725'
    - '#A9CC66'
  brandStrength: 0.0750518434215337
  lightness: 0.024493132485076785
  saturation: 0.5817737933248281
  rhythmicContrast: 0.3532100091688335
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5815856379922479
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Shayn Almeida
  email: Shayn@mac.com
  url: www.ShaynAlmeida.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/00709839-c73f-43c3-8caf-ca03f29ddf0a.jpg
name: Shayn Almeida
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/74dd415f-b228-49a3-ab2a-0bbee2986d3c.jpg
title: DJ. Yogi. Sonic Shaman. Holistic Alkhemist
purpose: []
