typography_spectrum: 0.5608748204540461
color:
  brandColors:
    - '#110f10'
    - '#7e638d'
    - '#4e5245'
    - '#c1bab5'
    - '#fefcf0'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.89429
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Shayn Almeida
  email: Shayn@mac.com
  url: www.ShaynAlmeida.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/00709839-c73f-43c3-8caf-ca03f29ddf0a.jpg
name: Shayn Almeida
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/74dd415f-b228-49a3-ab2a-0bbee2986d3c.jpg
title: Sonic Shaman. DJ. Holistic Alkhemist.
purpose: []
