name: Shayn Almeida
favicon: null
layout_spectrum: 0.89429
typography_spectrum: 0.5608748204540461
title: Shayn Almeida
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#110f10'
    - '#7e638d'
    - '#4e5245'
    - '#c1bab5'
    - '#fefcf0'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
