typography_spectrum: 0.5608748204540461
color:
  brandColors:
    - '#110f10'
    - '#7e638d'
    - '#4e5245'
    - '#c1bab5'
    - '#fefcf0'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.89429
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Shayn Almeida
  email: Shayn@mac.com
  url: www.ShaynAlmeida.com
name: Shayn Almeida
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: DJ. Yogi. Holistic Alchemist. Sonic Shaman.
purpose: []
