typography_spectrum: 0.0584024025592953
color:
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
  brandStrength: 0.14339591260068119
  lightness: 0.2808131768833846
  saturation: 0.9985827743075788
  rhythmicContrast: 0.4914590185508132
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3748072038870305
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Shayn Almeida
  email: Shayn@mac.com
  url: www.ShaynAlmeida.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/00709839-c73f-43c3-8caf-ca03f29ddf0a.jpg
name: Shayn Almeida
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/74dd415f-b228-49a3-ab2a-0bbee2986d3c.jpg
title: DJ. Yogi. Sonic Shaman. Holistic Alkhemist
purpose: []
